"""empty message

Revision ID: c43463df0c99
Revises: 0b7f61a20298
Create Date: 2019-03-18 20:58:07.421111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43463df0c99'
down_revision = '0b7f61a20298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_img', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['profile_img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'profile_img')
    # ### end Alembic commands ###
